### PR TITLE
Initial support for linux builds

### PR DESCRIPTION
**Pull request by mdaniel**
These are the two changes that I made to have the build succeed, but proving it would work on someone else's machine will require #10 or me to run a lot of "git clean" and wait the 4 hours for the build to re-run

One should also be aware that I built against the tag, but cherry-picked this change into `main`, so it's also not entirely apples-to-apples

So I'll put this in flight, and we'll update it as we learn more

### CODE REVIEW

**Comment by buffrr** [comment]
Great thanks! I will build this PR manually until we automate this

**Comment by mdaniel** [comment]
I wanted to provide an update, even though the build is still running (currently `[13237/51709] AR obj/third_party/vulkan-deps/spirv-tools/src/libspvtools.a`, so pretty far into it, IMHO)

I adapted [the brave-browser's "page-graph" Dockerfile](https://github.com/brave/brave-browser/blob/page-graph/Dockerfile) just a little bit and thus far it seems to be very close to what a linux contributor would need to participate (and, more importantly for this PR, shows that the changes are not totally off the rails)

* `apt-get install -y autogen automake libtool`
* install a more modern golang than ships with debian (I jumped right to 1.18.1 as is installed by Homebrew, but it's possible a lower version would work, too)
* clone `depot_tools` to `$HOME/depot_tools`
* add that dir, and `/usr/local/go/bin` to the `$PATH`
* put the beacon dir onto this branch
* :racing_car:

**Comment by buffrr** [comment]
Tested on linux and it works! Didn't break the build on macos or windows either. There are a few branding changes left for linux i'll create separate issues for those. 

> I adapted [the brave-browser's "page-graph" Dockerfile](https://github.com/brave/brave-browser/blob/page-graph/Dockerfile) just a little bit and thus far it seems to be very close to what a linux contributor would need to participate (and, more importantly for this PR, shows that the changes are not totally off the rails)

Sounds good would you like to include it in this PR as well before merging?

**Comment by mdaniel** [comment]
I'm glad to hear it. About 6 hours later, the Release build completed successfully, but then dumped core when I tried to run it outside of the container. I have the gdb backtrace if that's helpful, and I'm going to try and build the Debug version overnight to see if it behaves the same

If you already have **packaging** steps, I'd value knowing those -- I've actually never seen how Chromium gets turned into a .deb or .tar or whatever, short of the AUR and Debian machinery I linked to in the CI ticket. [The instructions](https://chromium.googlesource.com/chromium/src/+/main/docs/linux/dev_build_as_default_browser.md) make it seems like just running it from `src/out/Release` is commonplace or something

**Comment by buffrr** [comment]
> I'm glad to hear it. About 6 hours later, the Release build completed successfully, but then dumped core when I tried to run it outside of the container

I had no issues on a debug build but on a release build it crashed because it couldn't find the grpc lib. So ... we really need CI soon! Statically linking grpc [wasn't enabled for linux](https://chromium.googlesource.com/chromium/src/+/refs/heads/main/third_party/grpc/BUILD.gn#17) (i think this isn't an issue in debug builds because they're [component builds](https://chromium.googlesource.com/chromium/src.git/+/HEAD/docs/component_build.md)) 

I just appended `grpc_use_static_linking=true` at the end of `out/Release/args.gn` file to get release builds to work on linux. This won't be an issue because grpc usage will be eliminated anyways once #4 lands .. I'll be working on it this week (this arg would normally be added for release builds [here](https://github.com/imperviousinc/beacon/blob/main/tools/src/realbutil/build.go#L90) so it gets included to args.gn with having to add it manually)

> If you already have packaging steps, I'd value knowing those -- I've actually never seen how Chromium gets turned into a .deb

Sort of I believe chromium does .deb packaging [here](https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/BUILD.gn;l=239). You can try to build it using 

`autoninja -C out/Release chrome/installer`

([here's the code for chrome/installer target](https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/BUILD.gn;l=16?q=%22installer%2Flinux%5C%22%22&ss=chromium%2Fchromium%2Fsrc) depends on [chrome/installer/linux](https://source.chromium.org/chromium/chromium/src/+/main:chrome/installer/linux/BUILD.gn;l=239) )

it will fail because we still need to copy some beacon branding logos I believe. This PR is good for initial support I'll merge it and we can continue adding more things for packaging and branding. Thanks!

**Pull request merged**
